CREATE TABLE commit_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    complete BOOLEAN,
    user_id INTEGER REFERENCES commit_users(id)
    ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);
